package com.aliados.backend.entity;

public enum TipoNotificacion {
    NUEVO_TRABAJO,
    PROPUESTA_RECIBIDA,
    PROPUESTA_ACEPTADA,
    PROPUESTA_RECHAZADA,
    PROVEEDOR_ASIGNADO,
    TRABAJO_COMPLETADO,
    TRABAJO_COMPLETADO_PROVEEDOR,
    PRESUPUESTO_RECIBIDO,
    PRESUPUESTO_ACEPTADO,
    PRESUPUESTO_RECHAZADO,
    TRABAJO_EN_CURSO,
    TRABAJO_COLA_ACTIVADO,
    CALIFICACION_RECIBIDA,
    NUEVA_MUDANZA,
    MUDANZA_ACEPTADA,
    MUDANZA_CONTRAPROPUESTA,
    MUDANZA_CONTRAPROPUESTA_ACEPTADA,
    MUDANZA_CONTRAPROPUESTA_RECHAZADA,
    MUDANZA_INICIADA,
    MUDANZA_FINALIZADA,
    MUDANZA_COMPLETADA,
    TRABAJO_BUSCANDO_PROVEEDOR,
    TRABAJO_CANCELADO_SIN_PROVEEDOR,
    ANUNCIO,
    MENSAJE_CHAT
}
