-- ════════════════════════════════════════════════════════════════
-- V1 — Esquema inicial Aliados
-- Dinero como NUMERIC(12,2), fotos como JSONB, indices y unique de turno.
-- ════════════════════════════════════════════════════════════════

-- ── Oficios ──
CREATE TABLE oficios (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(255) NOT NULL UNIQUE,
    icono     VARCHAR(255) NOT NULL,
    activo    BOOLEAN NOT NULL,
    exclusivo BOOLEAN NOT NULL DEFAULT FALSE
);

-- ── Usuarios ──
CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(255) NOT NULL UNIQUE,
    email        VARCHAR(255) NOT NULL UNIQUE,
    role         VARCHAR(255) NOT NULL,
    nombre       VARCHAR(255) NOT NULL,
    telefono     VARCHAR(255),
    foto_perfil  VARCHAR(255),
    activo       BOOLEAN NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    oficio_id    BIGINT,
    matricula    VARCHAR(255),
    localidad    VARCHAR(255),
    status       VARCHAR(255) NOT NULL,
    last_seen_at TIMESTAMP(6),
    fcm_token    VARCHAR(255),
    CONSTRAINT fk_users_oficio FOREIGN KEY (oficio_id) REFERENCES oficios (id)
);

-- ── Tiers de mudanza ──
CREATE TABLE mudanza_tiers (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre               VARCHAR(255) NOT NULL UNIQUE,
    emoji                VARCHAR(255) NOT NULL,
    precio_base          NUMERIC(12, 2) NOT NULL,
    minutos_incluidos    INTEGER NOT NULL,
    precio_bloque30_min  NUMERIC(12, 2) NOT NULL,
    descripcion          VARCHAR(500) NOT NULL,
    descripcion_completa TEXT,
    activo               BOOLEAN NOT NULL,
    orden                INTEGER NOT NULL
);

-- ── Trabajos ──
CREATE TABLE trabajos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id              BIGINT NOT NULL,
    proveedor_id            BIGINT,
    oficio_id               BIGINT NOT NULL,
    estado                  VARCHAR(255) NOT NULL,
    descripcion             VARCHAR(1000) NOT NULL,
    direccion               VARCHAR(255) NOT NULL,
    latitud_cliente         DOUBLE PRECISION NOT NULL,
    longitud_cliente        DOUBLE PRECISION NOT NULL,
    latitud_proveedor       DOUBLE PRECISION,
    longitud_proveedor      DOUBLE PRECISION,
    direccion_destino       VARCHAR(255),
    latitud_destino         DOUBLE PRECISION,
    longitud_destino        DOUBLE PRECISION,
    tiempo_estimado_minutos INTEGER,
    precio_estimado         NUMERIC(12, 2),
    fotos                   JSONB,
    notificado_at           TIMESTAMP(6),
    proveedor_notificado_id BIGINT,
    created_at              TIMESTAMP(6) NOT NULL,
    accepted_at             TIMESTAMP(6),
    completed_at            TIMESTAMP(6),
    propuesto_at            TIMESTAMP(6),
    updated_at              TIMESTAMP(6) NOT NULL,
    motivo_cancelacion      VARCHAR(255),
    tarifa_visita           NUMERIC(12, 2),
    CONSTRAINT fk_trabajos_cliente   FOREIGN KEY (cliente_id)   REFERENCES users (id),
    CONSTRAINT fk_trabajos_proveedor FOREIGN KEY (proveedor_id) REFERENCES users (id),
    CONSTRAINT fk_trabajos_oficio    FOREIGN KEY (oficio_id)    REFERENCES oficios (id)
);

-- ── Mudanzas ──
CREATE TABLE mudanzas (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id             BIGINT NOT NULL,
    proveedor_id           BIGINT,
    tier_id                BIGINT NOT NULL,
    tier_original_id       BIGINT,
    estado                 VARCHAR(255) NOT NULL,
    direccion_origen       VARCHAR(255) NOT NULL,
    latitud_origen         DOUBLE PRECISION NOT NULL,
    longitud_origen        DOUBLE PRECISION NOT NULL,
    direccion_destino      VARCHAR(255) NOT NULL,
    latitud_destino        DOUBLE PRECISION NOT NULL,
    longitud_destino       DOUBLE PRECISION NOT NULL,
    pisos                  INTEGER NOT NULL,
    tiene_ascensor         BOOLEAN NOT NULL,
    cantidad_ambientes     INTEGER NOT NULL,
    fecha_deseada          DATE NOT NULL,
    fecha_confirmada       DATE,
    turno                  VARCHAR(255),
    fotos                  JSONB NOT NULL,
    notas_cliente          VARCHAR(1000),
    monto_base             NUMERIC(12, 2) NOT NULL,
    monto_final            NUMERIC(12, 2),
    monto_extra            NUMERIC(12, 2),
    comision_porcentaje    NUMERIC(12, 2) NOT NULL,
    comision_monto         NUMERIC(12, 2),
    monto_proveedor        NUMERIC(12, 2),
    motivo_contrapropuesta VARCHAR(500),
    fecha_original         DATE,
    iniciado_at            TIMESTAMP(6),
    finalizado_at          TIMESTAMP(6),
    duracion_real_minutos  INTEGER,
    bloques_extra          INTEGER,
    created_at             TIMESTAMP(6) NOT NULL,
    reservado_at           TIMESTAMP(6),
    accepted_at            TIMESTAMP(6),
    completed_at           TIMESTAMP(6),
    cancelled_at           TIMESTAMP(6),
    motivo_cancelacion     VARCHAR(500),
    updated_at             TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_mudanzas_cliente       FOREIGN KEY (cliente_id)       REFERENCES users (id),
    CONSTRAINT fk_mudanzas_proveedor     FOREIGN KEY (proveedor_id)     REFERENCES users (id),
    CONSTRAINT fk_mudanzas_tier          FOREIGN KEY (tier_id)          REFERENCES mudanza_tiers (id),
    CONSTRAINT fk_mudanzas_tier_original FOREIGN KEY (tier_original_id) REFERENCES mudanza_tiers (id)
);

-- ── Calificaciones ──
CREATE TABLE calificaciones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trabajo_id   BIGINT NOT NULL UNIQUE,
    cliente_id   BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL,
    estrellas    INTEGER NOT NULL,
    comentario   VARCHAR(500),
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_calif_trabajo   FOREIGN KEY (trabajo_id)   REFERENCES trabajos (id),
    CONSTRAINT fk_calif_cliente   FOREIGN KEY (cliente_id)   REFERENCES users (id),
    CONSTRAINT fk_calif_proveedor FOREIGN KEY (proveedor_id) REFERENCES users (id)
);

-- ── Notificaciones ──
CREATE TABLE notificaciones (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    tipo       VARCHAR(255) NOT NULL,
    titulo     VARCHAR(255) NOT NULL,
    mensaje    VARCHAR(255) NOT NULL,
    trabajo_id BIGINT,
    action_url VARCHAR(255),
    leida      BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ── Bug reports ──
CREATE TABLE bug_reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    categoria   VARCHAR(255) NOT NULL,
    titulo      VARCHAR(120) NOT NULL,
    descripcion VARCHAR(1000) NOT NULL,
    url         VARCHAR(500),
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_bug_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ════════════════════════════════════════════════════════════════
-- Indices
-- ════════════════════════════════════════════════════════════════

CREATE INDEX idx_users_oficio                    ON users (oficio_id);
CREATE INDEX idx_users_role_status_loc_oficio    ON users (role, status, localidad, oficio_id);

CREATE INDEX idx_trabajos_estado_oficio          ON trabajos (estado, oficio_id);
CREATE INDEX idx_trabajos_proveedor_estado       ON trabajos (proveedor_id, estado);
CREATE INDEX idx_trabajos_proveedor_notificado   ON trabajos (proveedor_notificado_id);
CREATE INDEX idx_trabajos_cliente                ON trabajos (cliente_id);

CREATE INDEX idx_mudanzas_estado                 ON mudanzas (estado);
CREATE INDEX idx_mudanzas_proveedor_estado       ON mudanzas (proveedor_id, estado);
CREATE INDEX idx_mudanzas_cliente                ON mudanzas (cliente_id);

-- Anti doble-booking: a lo sumo una mudanza vigente por (fecha, turno).
CREATE UNIQUE INDEX uq_mudanzas_fecha_turno ON mudanzas (fecha_confirmada, turno)
    WHERE estado NOT IN ('CANCELADO', 'COMPLETADO');

CREATE INDEX idx_calif_proveedor                 ON calificaciones (proveedor_id);

CREATE INDEX idx_notif_user_leida                ON notificaciones (user_id, leida);
CREATE INDEX idx_notif_user_created              ON notificaciones (user_id, created_at);

CREATE INDEX idx_bug_user                        ON bug_reports (user_id);
